#!/usr/bin/env bash

if [ $1 -eq 1 ]; then
  defaults write com.apple.finder CreateDesktop -boolean true && killall Finder
else
  defaults write com.apple.finder CreateDesktop -boolean false && killall Finder
fi
