#!/usr/bin/env bash

main() {
  local hide=$1
  osascript <<EOS >/dev/null
  tell application "System Preferences"
    activate
    reveal pane id "com.apple.preference.general"
  end tell

  delay 1

  tell application "System Events"
    tell window "一般" of process "System Preferences"
      set _checkBox to checkbox "メニューバーを自動的に表示/非表示"
      set isChecked to value of _checkBox as boolean
      if isChecked and $hide = 1 then
        click _checkBox
      else if not isChecked and $hide = 0 then
        click _checkBox
      end if
    end tell
  end tell

  quit application "System Preferences"
EOS
}
main $@
